### ISSUE TITLE
Error running ./build_lucene_index.sh VERSION LANGUAGE_CODE

### ISSUE THREAD

**Issue by miikargh** [dbpedia-spotlight/lucene-quickstarter#12]
Hi,

Thanks for making this handy docker system for building different language models!

For some reason, I'm not able to run the command ` ./build_lucene_index.sh 3.9 fi` without producing the following error:
```
root@181fd104935b:/mnt/dbpedia/lucene-quickstarter/scripts# ./build_lucene_index.sh 3.9 fi
fi 3.9
/mnt/dbpedia/lucene-quickstarter/i18n/fi/indexing_3.9.properties
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building DBpedia Spotlight Extraction Indexing 0.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> scala-maven-plugin:3.2.0:run (default-cli) @ index >>>
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven-3) @ index ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-java-newer-6) @ index ---
[INFO]
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ index ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /mnt/dbpedia/lucene-quickstarter/dbpedia-spotlight/index/src/main/resources
[INFO]
[INFO] --- scala-maven-plugin:3.2.0:add-source (scala-compile-first) @ index ---
[INFO] Add Source directory: /mnt/dbpedia/lucene-quickstarter/dbpedia-spotlight/index/src/main/scala
[INFO] Add Test Source directory: /mnt/dbpedia/lucene-quickstarter/dbpedia-spotlight/index/src/test/scala
[INFO]
[INFO] --- scala-maven-plugin:3.2.0:compile (scala-compile-first) @ index ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ index ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ index ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /mnt/dbpedia/lucene-quickstarter/dbpedia-spotlight/index/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ index ---
[INFO] No sources to compile
[INFO]
[INFO] <<< scala-maven-plugin:3.2.0:run (default-cli) @ index <<<
[INFO]
[INFO] --- scala-maven-plugin:3.2.0:run (default-cli) @ index ---
[INFO] launcher 'ExtractCandidateMap' selected => org.dbpedia.spotlight.util.ExtractCandidateMap
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.io.FileNotFoundException: /mnt/dbpedia/lucene-quickstarter/i18n/fi/indexing_3.9.properties (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.dbpedia.spotlight.util.IndexingConfiguration.<init>(IndexingConfiguration.scala:62)
	at org.dbpedia.spotlight.util.IndexingConfiguration.<init>(IndexingConfiguration.scala:56)
	at org.dbpedia.spotlight.util.ExtractCandidateMap$.main(ExtractCandidateMap.scala:396)
	at org.dbpedia.spotlight.util.ExtractCandidateMap.main(ExtractCandidateMap.scala)
	... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.776s
[INFO] Finished at: Tue Sep 25 09:10:26 UTC 2018
[INFO] Final Memory: 14M/134M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:run (default-cli) on project index: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Before running the above command I ran the commands
```
./download_wikipedia.sh fi
./download_dbpedia.sh 3.9 fi
```
which both worked fine.

What might be the problem here?

Cheers!

**Comment by zeppelinen** [comment]
If anyone else comes across this issue.
This error means that some of the files that should be downloaded in step `./download_dbpedia.sh` are missing.

For reference this is the files I've got for 2016-10:
```
-rw-r--r-- 1 root root 3.5G Mar 15  2017 article_categories_en.ttl
-rw-r--r-- 1 root root 226M Mar 15  2017 article_categories_en.ttl.bz2
-rw-r--r-- 1 root root 219M Apr  4  2017 disambiguations_en.ttl
-rw-r--r-- 1 root root  13M Apr  4  2017 disambiguations_en.ttl.bz2
-rw-r--r-- 1 root root 715M Apr  1  2017 instance_types_en.ttl
-rw-r--r-- 1 root root  41M Apr  1  2017 instance_types_en.ttl.bz2
-rw-r--r-- 1 root root 1.5G Mar 15  2017 labels_en.ttl
-rw-r--r-- 1 root root 182M Mar 15  2017 labels_en.ttl.bz2
-rw-r--r-- 1 root root 2.1G Jun 10  2017 short_abstracts_en.ttl
-rw-r--r-- 1 root root 523M Jun 10  2017 short_abstracts_en.ttl.bz2
-rw-r--r-- 1 root root 1.1G Jul  6  2017 transitive_redirects_en.ttl
-rw-r--r-- 1 root root 104M Jul  6  2017 transitive_redirects_en.ttl.bz2
```
